# Generated by Django 6.1 on 2026-09-04 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='jiger',
            new_name='discription',
        ),
    ]
