# Generated by Django 6.1 on 2026-09-04 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_rename_jiger_customer_discription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='discription',
        ),
        migrations.AddField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debt',
            name='kind',
            field=models.CharField(choices=[('debt', 'Долг'), ('payment', 'Оплата')], default='debt', max_length=10),
        ),
        migrations.AlterField(
            model_name='debt',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='Book.customer'),
        ),
    ]
