# Generated by Django 6.1 on 2026-09-16 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_remove_customer_discription_customer_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debt',
            old_name='time',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='kind',
        ),
        migrations.AlterField(
            model_name='debt',
            name='amount',
            field=models.DecimalField(decimal_places=5, max_digits=25),
        ),
        migrations.AlterField(
            model_name='debt',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to='Book.customer'),
        ),
    ]
