# Generated by Django 6.1 on 2026-09-16 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_rename_time_debt_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='Book.customer'),
        ),
    ]
