# Generated by Django 6.1 on 2026-09-18 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0005_alter_debt_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='debt',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debt',
            name='type',
            field=models.CharField(choices=[('debt', 'Долг'), ('payment', 'Оплата')], default='debt', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='debt',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=25),
        ),
    ]
